version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: phalconphp-memcached

    mongo:
      image: mongo
      restart: always
      volumes:
        - ./app/:/application
      command: mongod --bind_ip 0.0.0.0
      ports:
        - 27017:27017

    redis:
      image: redis:alpine
      container_name: phalconphp-redis
      ports:
        - 6379:6379
    
    redis_browser:
      image: birkof/redis-browser
      command: --url redis://redis:6379
      ports:
        - 4567:4567

    mysql:
      image: mysql:5.7.12
      container_name: phalconphp-mysql
      working_dir: /application
      volumes:
        - ./app/:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=phalcon_db
        - MYSQL_USER=phalcon_db_user
        - MYSQL_PASSWORD=password
      ports:
        - "3306:3306"

    postgres:
      image: postgres:11.1-alpine
      container_name: phalconphp-postgres
      working_dir: /application
      volumes:
        - ./app/:/application
      environment:
        - POSTGRES_USER=phalcon_db_user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=phalcon_db

    webserver:
      image: nginx:alpine
      container_name: phalconphp-webserver
      working_dir: /application
      volumes:
          - ./app/:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php_fpm:
      build: phpdocker/php-fpm
      container_name: phalconphp-php-fpm
      working_dir: /application
      volumes:
        - ./app/:/application
        - ./app/var/cache/session/:/var/lib/php/session/
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
